# Analysis Pipeline Configuration Template
# Copy this file and modify as needed for your analysis

# Data loading settings
data:
  cache_enabled: true  # Enable caching for faster repeated analyses
  
# Analyzer settings
analyzers:
  communication: true      # Communication patterns and network structure
  information_flow: true   # Information sharing and asymmetry
  task_performance: true   # Task completion and efficiency
  strategy: true          # Strategic behaviors (negotiation, deception, reciprocity)
  
# Visualization settings
visualizations:
  create_all: true              # Create all core visualizations
  style: 'seaborn-v0_8-darkgrid'  # Matplotlib style
  dpi: 300                      # Resolution for saved figures
  
# Output settings
output:
  formats: ['json', 'txt']  # Output formats: json, txt, csv
  include_raw_data: false   # Include raw event data in outputs
  
# Advanced settings
advanced:
  # Thresholds for analysis
  deception_threshold: 0.2      # Threshold for identifying deceptive agents
  high_activity_threshold: 1.5  # Multiplier for identifying high activity
  
  # Network analysis
  min_edge_weight: 1  # Minimum interactions to show edge in network
  
  # Performance metrics
  efficiency_window: 3  # Rounds to consider for efficiency calculations